---
ID: "7aa54535-3a5f-4d93-81ec-11b88ba99e90"
Parent: "c6a06bbf-b6b9-407c-b9b0-02a4ae4dc389"
Template: "c6a06bbf-b6b9-407c-b9b0-02a4ae4dc389"
Path: /sitecore/templates/Aveva/Dropdown Item/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{9B27FC46-548D-4FA5-AAD5-24A130AC495C}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160524T095024Z
    - ID: "359f846e-0435-411f-b04d-89f07e598d15"
      Hint: Name
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
